name: neural-simp
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h716150d_1
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.3.5
      - aiohttp==3.10.1
      - aiosignal==1.3.1
      - attrs==24.2.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==2.20.0
      - dill==0.3.8
      - filelock==3.15.4
      - fonttools==4.61.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - huggingface-hub==0.24.5
      - idna==3.7
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.3
      - neural-mesh-simplification==0.1.0
      - numpy==1.26.4
      - packaging==24.1
      - pandas==2.2.2
      - pillow==12.0.0
      - pluggy==1.5.0
      - propcache==0.4.1
      - psutil==6.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pyparsing==3.1.2
      - pytest==8.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - rtree==1.3.0
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - setuptools==72.1.0
      - six==1.16.0
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - torch==2.4.0+cu121
      - torch-cluster==1.6.3+pt24cu121
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2+pt24cu121
      - torch-sparse==0.6.18+pt24cpu
      - torchaudio==2.4.0+cpu
      - torchvision==0.19.0+cpu
      - tqdm==4.66.5
      - trimesh==4.4.4
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - wheel==0.43.0
      - xxhash==3.4.1
      - yarl==1.9.4
prefix: C:\Users\luky7\miniconda3\envs\neural-simp
