name: thesis
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - asttokens==3.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - dash==3.3.0
      - decorator==5.2.1
      - executing==2.2.1
      - fast-simplification==0.1.13
      - fastjsonschema==2.21.2
      - flask==3.1.2
      - fonttools==4.61.1
      - idna==3.11
      - importlib-metadata==8.7.1
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - meshoptimizer==0.2.20a5
      - narwhals==2.14.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==2.4.0
      - open3d==0.19.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pillow==12.0.0
      - platformdirs==4.5.1
      - plotly==6.5.0
      - pooch==1.8.2
      - prompt-toolkit==3.0.52
      - psutil==7.2.1
      - pure-eval==0.2.3
      - pyfqmr==0.5.0
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyvista==0.46.4
      - referencing==0.37.0
      - requests==2.32.5
      - retrying==1.4.2
      - rpds-py==0.30.0
      - scooby==0.11.0
      - six==1.17.0
      - stack-data==0.6.3
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - vtk==9.5.2
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - zipp==3.23.0
prefix: C:\Users\luky7\miniconda3\envs\thesis
